name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - 
        name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ghtoken }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to soerens registry
        uses: docker/login-action@v1 
        with:
          registry: docker.soerensserver.xyz
          username:  ${{ secrets.username }}
          password: ${{ secrets.password }} 
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.soerensserver.xyz/geolocationapi-${{ steps.extract_branch.outputs.branch }}
